version: "3.9"

services:
  postgresdb:
    image: postgres:12-alpine
    container_name: postgresdb
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=jobberman
    networks:
      - jobberman-network
    ports:
      - "5432:5432"
    healthcheck:
      # test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgresdb:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - port=1337
    ports:
      - "${port}:1337"
    env_file:
      - .env
    networks:
      - jobberman-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1337/healthcheck"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

networks:
  jobberman-network:
    name: jobberman-network
